In [74]:

import requests, numpy as np, pandas as pd
from bs4 import BeautifulSoup
from pprint import pprint

In [11]:

html_location = "C:\\Users\\karan\\Documents\\Cricket-Analytics\\IPL\\Data\\Ball by Ball (html)\\"

In [ ]:

names_of_htmls = ['']

In [10]:

# Get the HTML content of the website
response = requests.get('https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/chennai-super-kings-vs-kolkata-knight-riders-61st-match-1359535/ball-by-ball-commentary')

# Parse the HTML content using Beautiful Soup
soup = BeautifulSoup(response.content, 'html.parser')
soup_innings = BeautifulSoup(response.content, 'html5lib')

# pprint soup to see what is going on here
pprint(soup_innings)

FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

In [7]:

# Find all the ball-by-ball commentary elements
commentary_elements = soup.find_all('div', class_='commentary')

pprint(commentary_elements)

[]

In [ ]:
# Extract the data from the commentary elements
data = []
for commentary_element in commentary_elements:
    # Extract the over number
    over_number = commentary_element.find('span', class_='over').text

    # Extract the ball number
    ball_number = commentary_element.find('span', class_='ball').text

    # Extract the batsman
    batsman = commentary_element.find('span', class_='batsman').text

    # Extract the bowler
    bowler = commentary_element.find('span', class_='bowler').text

    # Extract the delivery type
    delivery_type = commentary_element.find('span', class_='delivery-type').text

    # Extract the runs scored
    runs_scored = commentary_element.find('span', class_='runs').text

    # Extract the wickets taken
    wickets_taken = commentary_element.find('span', class_='wickets').text

    # Extract the extras
    extras = commentary_element.find('span', class_='extras').text

    # Extract the total runs
    total_runs = commentary_element.find('span', class_='total-runs').text

    # Append the data to the list
    data.append({
        'over_number': over_number,
        'ball_number': ball_number,
        'batsman': batsman,
        'bowler': bowler,
        'delivery_type': delivery_type,
        'runs_scored': runs_scored,
        'wickets_taken': wickets_taken,
        'extras': extras,
        'total_runs': total_runs
    })

In [4]:


# Print the data
print(data)

[]

In [ ]:
### CRICINFOR COMMENTARY SCRAPER

In [ ]:
### https://github.com/AlbertBannister/cricinfo-commentary-scraper

In [3]:

import requests
import json
import pandas as pd
from pprint import pprint

In [27]:

def scrape_chunk(series_id, match_id, from_over, inning_num):
    """
    scrapes a chunk of commentary via AJAX request. The commentary comes in two over pieces, going backwards
    from the from_over parameter 
    e.g if from_over = 2 then we will get overs 1 and 2 which will have ball details looking like 0.1, 0.2, 1.1, 1.2 etc
    """
    url = f"https://hs-consumer-api.espncricinfo.com/v1/pages/match/comments?lang=en&seriesId={series_id}&matchId={match_id}&inningNumber={inning_num}&commentType=ALL&fromInningOver={from_over}"
    #print(url)
    resp = requests.get(url)
    resp_json = json.loads(resp.text)
    chunk_data = resp_json['comments']
    return chunk_data

In [42]:

G61_url = "https://www.espncricinfo.com/series/indian-premier-league-2023-1345038/chennai-super-kings-vs-kolkata-knight-riders-61st-match-1359535/ball-by-ball-commentary"

#series_id = 1239527 
series_id = 1345038

#match_id = 1239543
match_id = 1359535

end_over = 20
inning_num = 1

two_overs = scrape_chunk(series_id, match_id, end_over, inning_num)

print(type(two_overs))
print(len(two_overs))

# len means that there are x number of balls in that two-over chunk ending at from_over

<class 'list'>
15

In [43]:

pprint(two_overs[0])

{'_uid': 42734165,
 'ballNumber': 8,
 'ballsActual': None,
 'ballsUnique': None,
 'batsmanPlayerId': 7593,
 'batsmanRuns': 2,
 'batsmanStatText': None,
 'bowlerPlayerId': 107007,
 'bowlerStatText': None,
 'byes': 0,
 'commentImages': [],
 'commentPostTextItems': [{'html': '<b>9.22pm</b> It did look like that on the '
                                   'telly, and Varun confirmed that it might '
                                   'have got better to bat on towards the end '
                                   'of the first innings. Perhaps there is '
                                   "some dew or moisture on the pitch. Let's "
                                   'see how the chase goes. Be back soon.',
                           'type': 'HTML'},
                          {'html': '<b>9.20pm</b> CV Varun says, and this is '
                                   'not verbatim: A good season for me so far. '
                                   'The pitch was sticky early on, but I think '
                                   'it became flat after the second timeout. I '
                                   'have been working on my legspin this '
                                   'season, and thankful that it has worked '
                                   'well. Last season I used to bowl it '
                                   'cross-seam so I thought I will mix it up '
                                   'with the seam one, and yes, it is creating '
                                   'doubts.',
                           'type': 'HTML'},
                          {'html': "<b>9.19pm</b> That's CSK's lowest score "
                                   'this IPL. A challenging pitch on which the '
                                   'KKR spinners bowled well. There was just '
                                   'one boundary from overs 6 through 15. '
                                   'Shivam Dube has shown he is not just a '
                                   'brute spin hitter. He has played a planned '
                                   'innings here',
                           'type': 'HTML'}],
 'commentPreTextItems': None,
 'commentTextItems': [{'html': 'nearly nails the yorker, drilled hard, '
                               'straight of long-on. Comes back for two',
                       'type': 'HTML'}],
 'commentVideos': [],
 'dismissalText': None,
 'dismissalType': None,
 'events': [],
 'id': 42734165,
 'inningNumber': 1,
 'isFour': False,
 'isSix': False,
 'isWicket': False,
 'legbyes': 0,
 'modified': '2023-05-14T15:49:02.000Z',
 'noballs': 0,
 'outPlayerId': None,
 'over': {'ballLimit': 120,
          'isComplete': True,
          'isMaiden': False,
          'isSuperOver': False,
          'overEndBatsmen': [{'balls': 3,
                              'fours': 0,
                              'player': {'battingName': 'MS Dhoni',
                                         'battingStyles': ['rhb'],
                                         'bowlingStyles': ['rm'],
                                         'countryTeamId': 6,
                                         'dateOfBirth': {'date': 7,
                                                         'month': 7,
                                                         'year': 1981},
                                         'dateOfDeath': None,
                                         'fieldingName': 'Dhoni',
                                         'gender': 'M',
                                         'id': 7593,
                                         'image': {'caption': 'MS Dhoni '
                                                              'portrait',
                                                   'credit': 'Getty Images',
                                                   'height': 202,
                                                   'id': 302402,
                                                   'longCaption': 'MS Dhoni '
                                                                  'portrait, '
                                                                  'April 2020',
                                                   'objectId': 1220600,
                                                   'peerUrls': None,
                                                   'photographer': None,
                                                   'slug': 'ms-dhoni-portrait',
                                                   'url': '/db/PICTURES/CMS/302400/302402.jpg',
                                                   'width': 160},
                                         'imageUrl': '/db/PICTURES/CMS/302400/302402.jpg',
                                         'indexName': 'Dhoni, MS',
                                         'longBattingStyles': ['right-hand '
                                                               'bat'],
                                         'longBowlingStyles': ['right-arm '
                                                               'medium'],
                                         'longName': 'MS Dhoni',
                                         'mobileName': 'Dhoni',
                                         'name': 'MS Dhoni',
                                         'objectId': 28081,
                                         'playerRoleTypeIds': [7],
                                         'playingRoles': ['wicketkeeper '
                                                          'batter'],
                                         'slug': 'ms-dhoni'},
                              'runs': 2,
                              'sixes': 0},
                             {'balls': 34,
                              'fours': 1,
                              'player': {'battingName': 'S Dube',
                                         'battingStyles': ['lhb'],
                                         'bowlingStyles': ['rm'],
                                         'countryTeamId': 6,
                                         'dateOfBirth': {'date': 26,
                                                         'month': 6,
                                                         'year': 1993},
                                         'dateOfDeath': None,
                                         'fieldingName': 'Dube',
                                         'gender': 'M',
                                         'id': 74975,
                                         'image': {'caption': 'Dube player '
                                                              'portrait',
                                                   'credit': 'Google',
                                                   'height': 200,
                                                   'id': 356768,
                                                   'longCaption': 'Dube player '
                                                                  'portrait',
                                                   'objectId': 1364963,
                                                   'peerUrls': None,
                                                   'photographer': None,
                                                   'slug': 'dube-player-portrait',
                                                   'url': '/db/PICTURES/CMS/356700/356768.1.png',
                                                   'width': 160},
                                         'imageUrl': '/db/PICTURES/CMS/356700/356768.1.png',
                                         'indexName': 'Dube,S',
                                         'longBattingStyles': ['left-hand bat'],
                                         'longBowlingStyles': ['right-arm '
                                                               'medium'],
                                         'longName': 'Shivam Dube',
                                         'mobileName': 'Dube',
                                         'name': 'S Dube',
                                         'objectId': 714451,
                                         'playerRoleTypeIds': [5],
                                         'playingRoles': ['allrounder'],
                                         'slug': 'shivam-dube'},
                              'runs': 48,
                              'sixes': 3}],
          'overEndBowlers': [{'balls': 24,
                              'conceded': 30,
                              'currentType': 1,
                              'maidens': 0,
                              'overs': 4,
                              'player': {'battingName': 'VG Arora',
                                         'battingStyles': ['rhb'],
                                         'bowlingStyles': ['rfm'],
                                         'countryTeamId': 6,
                                         'dateOfBirth': {'date': 14,
                                                         'month': 12,
                                                         'year': 1997},
                                         'dateOfDeath': None,
                                         'fieldingName': 'Arora',
                                         'gender': 'M',
                                         'id': 107007,
                                         'image': {'caption': 'Vaibhav Arora '
                                                              'player portrait',
                                                   'credit': 'KKR',
                                                   'height': 206,
                                                   'id': 357019,
                                                   'longCaption': 'Vaibhav '
                                                                  'Arora '
                                                                  'player '
                                                                  'portrait',
                                                   'objectId': 1365534,
                                                   'peerUrls': None,
                                                   'photographer': None,
                                                   'slug': 'vaibhav-arora-player-portrait',
                                                   'url': '/db/PICTURES/CMS/357000/357019.1.png',
                                                   'width': 160},
                                         'imageUrl': '/db/PICTURES/CMS/357000/357019.1.png',
                                         'indexName': 'Arora,VG',
                                         'longBattingStyles': ['right-hand '
                                                               'bat'],
                                         'longBowlingStyles': ['right-arm '
                                                               'fast-medium'],
                                         'longName': 'Vaibhav Arora',
                                         'mobileName': 'Arora',
                                         'name': 'VG Arora',
                                         'objectId': 1209292,
                                         'playerRoleTypeIds': [4],
                                         'playingRoles': ['bowler'],
                                         'slug': 'vaibhav-arora'},
                              'wickets': 1},
                             {'balls': 18,
                              'conceded': 15,
                              'currentType': 2,
                              'maidens': 0,
                              'overs': 3,
                              'player': {'battingName': 'SN Thakur',
                                         'battingStyles': ['rhb'],
                                         'bowlingStyles': ['rm'],
                                         'countryTeamId': 6,
                                         'dateOfBirth': {'date': 16,
                                                         'month': 10,
                                                         'year': 1991},
                                         'dateOfDeath': None,
                                         'fieldingName': 'Thakur',
                                         'gender': 'M',
                                         'id': 63477,
                                         'image': {'caption': 'Shardul Thakur '
                                                              'portrait',
                                                   'credit': 'Getty Images',
                                                   'height': 201,
                                                   'id': 302372,
                                                   'longCaption': 'Shardul '
                                                                  'Thakur '
                                                                  'portrait, '
                                                                  'April 2020',
                                                   'objectId': 1220568,
                                                   'peerUrls': None,
                                                   'photographer': None,
                                                   'slug': 'shardul-thakur-portrait',
                                                   'url': '/db/PICTURES/CMS/302300/302372.jpg',
                                                   'width': 160},
                                         'imageUrl': '/db/PICTURES/CMS/302300/302372.jpg',
                                         'indexName': 'Thakur, SN',
                                         'longBattingStyles': ['right-hand '
                                                               'bat'],
                                         'longBowlingStyles': ['right-arm '
                                                               'medium'],
                                         'longName': 'Shardul Thakur',
                                         'mobileName': 'Thakur',
                                         'name': 'SN Thakur',
                                         'objectId': 475281,
                                         'playerRoleTypeIds': [4],
                                         'playingRoles': ['bowler'],
                                         'slug': 'shardul-thakur'},
                              'wickets': 1}],
          'overLimit': 20,
          'overNumber': 20,
          'overRuns': 9,
          'overWickets': 1,
          'rollover': None,
          'target': 0,
          'team': {'abbreviation': 'CSK',
                   'id': 4343,
                   'image': {'caption': 'Chennai Super Kings logo',
                             'credit': None,
                             'height': 500,
                             'id': 313421,
                             'longCaption': 'Chennai Super Kings logo',
                             'objectId': 1241880,
                             'peerUrls': None,
                             'photographer': None,
                             'slug': 'chennai-super-kings-logo',
                             'url': '/db/PICTURES/CMS/313400/313421.logo.png',
                             'width': 500},
                   'imageUrl': '/db/PICTURES/CMS/313400/313421.logo.png',
                   'isCountry': False,
                   'longName': 'Chennai Super Kings',
                   'name': 'Super Kings',
                   'objectId': 335974,
                   'primaryColor': '#fdb913',
                   'scribeId': 335974,
                   'slug': 'chennai-super-kings',
                   'unofficialName': 'Chennai'},
          'totalRuns': 144,
          'totalWickets': 6},
 'overNumber': 20,
 'oversActual': 19.6,
 'oversUnique': 19.08,
 'penalties': 0,
 'predictions': {'score': 144, 'winProbability': 22.64},
 'timestamp': '2023-05-14T15:48:57.000Z',
 'title': 'Arora to Dhoni',
 'totalInningRuns': 144,
 'totalInningWickets': 6,
 'totalRuns': 2,
 'wagonZone': 4,
 'wides': 0}

In [45]:

print()

two_overs_keys = list(two_overs[0].keys())
print(two_overs_keys)

print()

['_uid', 'id', 'inningNumber', 'ballsActual', 'ballsUnique', 'oversUnique', 'oversActual', 'overNumber', 'ballNumber', 'totalRuns', 'batsmanRuns', 'isFour', 'isSix', 'isWicket', 'dismissalType', 'byes', 'legbyes', 'wides', 'noballs', 'penalties', 'wagonZone', 'timestamp', 'modified', 'batsmanPlayerId', 'bowlerPlayerId', 'outPlayerId', 'totalInningRuns', 'totalInningWickets', 'predictions', 'title', 'dismissalText', 'commentPreTextItems', 'commentTextItems', 'commentPostTextItems', 'commentVideos', 'commentImages', 'events', 'over', 'batsmanStatText', 'bowlerStatText']

In [88]:

print(f'Balls in this tow over chunk are {len(two_overs)}')

Balls in this tow over chunk are 15

In [150]:

two_overs = scrape_chunk(series_id, match_id, 20, 2)
print(len(two_overs))
print(two_overs)

4
[{'_uid': 42734634, 'id': 42734634, 'inningNumber': 2, 'ballsActual': None, 'ballsUnique': None, 'oversUnique': 18.04, 'oversActual': 18.3, 'overNumber': 19, 'ballNumber': 4, 'totalRuns': 4, 'batsmanRuns': 4, 'isFour': True, 'isSix': False, 'isWicket': False, 'dismissalType': None, 'byes': 0, 'legbyes': 0, 'wides': 0, 'noballs': 0, 'penalties': 0, 'wagonZone': 1, 'timestamp': '2023-05-14T17:37:53.000Z', 'modified': '2023-05-14T17:37:59.000Z', 'batsmanPlayerId': 70411, 'bowlerPlayerId': 80607, 'outPlayerId': None, 'totalInningRuns': 147, 'totalInningWickets': 4, 'predictions': {'score': 163, 'winProbability': 100}, 'title': 'Deshpande to Rana', 'dismissalText': None, 'commentPreTextItems': None, 'commentTextItems': [{'type': 'HTML', 'html': "that's the game. Slower ball, but too full, and Rana goes for the drive. Gets a thick edge that clears short third"}], 'commentPostTextItems': [{'type': 'HTML', 'html': 'And that ends our offerings for you tonight. This result gives Mumbai Indians hope of finishing in the top two if they can win their last two matches. CSK still not through, KKR still not out. The IPL remains wide open. Not much dew so far in Chennai but tonight it made a big difference. That might confuse teams with what to do in the playoffs. A big week coming up. For now, though, good night and good luck.'}, {'type': 'HTML', 'html': '<b>11.30pm Rinku Singh is the Player of the Match</b>. He says, and this is not verbatim: We lost three wickets early, so we decided we will take this deep. I bat at 5, 6 in domestic cricket too so the experience helped me. I have worked hard, really hard, to get batting well, which is what gives me confidence.'}, {'type': 'HTML', 'html': "<b>11.27pm</b> <b>Nitish Rana</b> says, and this is not verbatim: Chandu sir [Pandit, KKR coach] asked for a heavy roller, which I didn't want. I felt the heavy roller might break the pitch, but it settled the pitch completely. The ball didn't turn in the second innings. Credit to our spinners for how well they bowled. I always felt that if I or Rinku could hold one end up, we will chase this down. That's what happeened."}, {'type': 'HTML', 'html': "<b>11.10pm</b> <b>MS Dhoni</b> says, and this is not verbatim: The minute we bowled the first ball in the second innings, we knew we needed 180. But there was no way we could have got 180 on that pitch. The dew made a big difference in the second innings. We can't really blame any of our bowlers. Just that the conditions had a big impact on the game. Very happy with what Shivam has done, but important that he is not satisfied and keeps improving. Chahar swings the ball, he knows what fields to take, and he bowls accordingly."}, {'type': 'HTML', 'html': '<b>11.08pm</b> KKR have strolled this chase despite losing three wickets inn the powerplay. Rana and Rinku never looked under any pressure despite coming together at 3 for not much. Both of them scored sensible fifites to see them through. So CSK are not yet officially through, and KKR are not yet officially out.'}], 'commentVideos': [{'id': 130835, 'objectId': 1375785, 'scribeId': 37648963, 'statusTypeId': 3, 'slug': 'watch-kkr-win-in-chennai-for-first-since-since-2012', 'title': 'Watch - KKR win in Chennai for first since since 2012', 'subTitle': '', 'seoTitle': 'Watch - KKR win in Chennai for first since since 2012', 'summary': '', 'duration': 47, 'genreId': 37, 'genreType': 'HIGHLIGHTS', 'genreName': 'Highlights', 'publishedAt': '2023-05-14T00:00:00.000Z', 'modifiedAt': '2023-05-14T18:32:27.000Z', 'recordedAt': '2023-05-14T00:00:00.000Z', 'expireAt': '2023-05-17T18:07:00.000Z', 'countryCodes': ['US', 'AS', 'GU', 'MP', 'PR', 'UM', 'VI'], 'imageUrl': '/media/motion/fastclipper/2023/0514/evc_IPLUS_20230514_no_event_name_2d634726_728e_451f_917f_8d70f8688fba_18281/evc_IPLUS_20230514_no_event_name_2d634726_728e_451f_917f_8d70f8688fba_18281.jpg', 'origin': {'type': 'CLIP'}, 'assetId': 'evc_IPLUS_20230514_no_event_name_2d634726_728e_451f_917f_8d70f8688fba_18281', 'scribeMongoId': '64612380be6ab325d44fbbb1', 'language': 'en'}, {'id': 130834, 'objectId': 1375782, 'scribeId': 37648936, 'statusTypeId': 3, 'slug': 'watch-nitish-rana-wraps-up-victory-with-a-four', 'title': 'Watch - Nitish Rana wraps up victory with a four', 'subTitle': '', 'seoTitle': 'Watch - Nitish Rana wraps up victory with a four', 'summary': "KKR's winning moment", 'duration': 47, 'genreId': 37, 'genreType': 'HIGHLIGHTS', 'genreName': 'Highlights', 'publishedAt': '2023-05-14T00:00:00.000Z', 'modifiedAt': '2023-05-14T18:14:18.000Z', 'recordedAt': '2023-05-14T00:00:00.000Z', 'expireAt': '2023-05-17T18:03:00.000Z', 'countryCodes': ['GB', 'IE'], 'imageUrl': '/media/motion/fastclipper/2023/0514/evc_IPLUK_20230514_no_event_name_9e42047a_c14f_4daf_a6a7_0ad0417a560d_18301/evc_IPLUK_20230514_no_event_name_9e42047a_c14f_4daf_a6a7_0ad0417a560d_18301.jpg', 'origin': {'type': 'CLIP'}, 'assetId': 'evc_IPLUK_20230514_no_event_name_9e42047a_c14f_4daf_a6a7_0ad0417a560d_18301', 'scribeMongoId': '64612284be6ab325d44fb5a0', 'language': 'en'}], 'commentImages': [{'id': 360079, 'objectId': 1375796, 'slug': 'nitish-rana-shakes-hands-with-ms-dhoni-and-ravindra-jadeja', 'url': '/db/PICTURES/CMS/360000/360079.jpg', 'width': 1400, 'height': 933, 'caption': 'Nitish Rana shakes hands with MS Dhoni and Ravindra Jadeja', 'longCaption': 'Nitish Rana shakes hands with MS Dhoni and Ravindra Jadeja, Chennai Super Kings vs Kolkata Knight Riders, IPL 2023, Chennai, May 14, 2023', 'credit': 'BCCI', 'photographer': None, 'peerUrls': {'FILM': '/db/PICTURES/CMS/360000/360079.jpg', 'WIDE': '/db/PICTURES/CMS/360000/360079.6.jpg', 'SQUARE': '/db/PICTURES/CMS/360000/360079.10.jpg'}, 'dateTaken': '2023-05-14T00:00:00.000Z', 'capturedOn': {'year': 2023, 'month': 5, 'date': 14}}, {'id': 360082, 'objectId': 1375799, 'slug': 'ms-dhoni-practiced-his-tennis-forehand-as-he-hit-some-balls-to-the-crowd-after-the-game', 'url': '/db/PICTURES/CMS/360000/360082.jpg', 'width': 1400, 'height': 933, 'caption': 'MS Dhoni practiced his tennis forehand as he hit some balls to the crowd after the game', 'longCaption': 'MS Dhoni practiced his tennis forehand as he hit some balls to the crowd after the game, Chennai Super Kings vs Kolkata Knight Riders, IPL 2023, Chennai, May 14, 2023', 'credit': 'BCCI', 'photographer': None, 'peerUrls': {'FILM': '/db/PICTURES/CMS/360000/360082.jpg', 'WIDE': '/db/PICTURES/CMS/360000/360082.6.jpg', 'SQUARE': '/db/PICTURES/CMS/360000/360082.10.jpg'}, 'dateTaken': '2023-05-14T00:00:00.000Z', 'capturedOn': {'year': 2023, 'month': 5, 'date': 14}}, {'id': 360081, 'objectId': 1375798, 'slug': 'ms-dhoni-had-a-brace-strapped-on-his-knee-as-he-did-a-lap-of-the-chepauk', 'url': '/db/PICTURES/CMS/360000/360081.jpg', 'width': 1400, 'height': 933, 'caption': 'MS Dhoni had a brace strapped on his knee as he did a lap of the Chepauk', 'longCaption': 'MS Dhoni had a brace strapped on his knee as he did a lap of the Chepauk, Chennai Super Kings vs Kolkata Knight Riders, IPL 2023, Chennai, May 14, 2023', 'credit': 'BCCI', 'photographer': None, 'peerUrls': {'FILM': '/db/PICTURES/CMS/360000/360081.jpg', 'WIDE': '/db/PICTURES/CMS/360000/360081.6.jpg', 'SQUARE': '/db/PICTURES/CMS/360000/360081.10.jpg'}, 'dateTaken': '2023-05-14T00:00:00.000Z', 'capturedOn': {'year': 2023, 'month': 5, 'date': 14}}, {'id': 360080, 'objectId': 1375797, 'slug': 'ms-dhoni-signs-sunil-gavaskar-s-shirt', 'url': '/db/PICTURES/CMS/360000/360080.jpg', 'width': 1400, 'height': 933, 'caption': "MS Dhoni signs Sunil Gavaskar's shirt", 'longCaption': "MS Dhoni signs Sunil Gavaskar's shirt, Chennai Super Kings vs Kolkata Knight Riders, IPL 2023, Chennai, May 14, 2023", 'credit': 'BCCI', 'photographer': None, 'peerUrls': {'FILM': '/db/PICTURES/CMS/360000/360080.jpg', 'WIDE': '/db/PICTURES/CMS/360000/360080.6.jpg', 'SQUARE': '/db/PICTURES/CMS/360000/360080.10.jpg'}, 'dateTaken': '2023-05-14T00:00:00.000Z', 'capturedOn': {'year': 2023, 'month': 5, 'date': 14}}], 'events': [], 'over': None, 'batsmanStatText': None, 'bowlerStatText': None}, {'_uid': 42734632, 'id': 42734632, 'inningNumber': 2, 'ballsActual': None, 'ballsUnique': None, 'oversUnique': 18.03, 'oversActual': 18.3, 'overNumber': 19, 'ballNumber': 3, 'totalRuns': 1, 'batsmanRuns': 0, 'isFour': False, 'isSix': False, 'isWicket': False, 'dismissalType': None, 'byes': 0, 'legbyes': 0, 'wides': 1, 'noballs': 0, 'penalties': 0, 'wagonZone': 0, 'timestamp': '2023-05-14T17:37:13.000Z', 'modified': '2023-05-14T17:37:16.000Z', 'batsmanPlayerId': 70411, 'bowlerPlayerId': 80607, 'outPlayerId': None, 'totalInningRuns': 143, 'totalInningWickets': 4, 'predictions': {'score': 161, 'winProbability': 99.77}, 'title': 'Deshpande to Rana', 'dismissalText': None, 'commentPreTextItems': None, 'commentTextItems': [{'type': 'HTML', 'html': 'full and wide, too wide'}], 'commentPostTextItems': None, 'commentVideos': [], 'commentImages': [], 'events': [], 'over': None, 'batsmanStatText': None, 'bowlerStatText': None}, {'_uid': 42734631, 'id': 42734631, 'inningNumber': 2, 'ballsActual': None, 'ballsUnique': None, 'oversUnique': 18.02, 'oversActual': 18.2, 'overNumber': 19, 'ballNumber': 2, 'totalRuns': 0, 'batsmanRuns': 0, 'isFour': False, 'isSix': False, 'isWicket': False, 'dismissalType': None, 'byes': 0, 'legbyes': 0, 'wides': 0, 'noballs': 0, 'penalties': 0, 'wagonZone': 0, 'timestamp': '2023-05-14T17:36:43.000Z', 'modified': '2023-05-14T17:36:47.000Z', 'batsmanPlayerId': 70411, 'bowlerPlayerId': 80607, 'outPlayerId': None, 'totalInningRuns': 142, 'totalInningWickets': 4, 'predictions': {'score': 160, 'winProbability': 99.7}, 'title': 'Deshpande to Rana', 'dismissalText': None, 'commentPreTextItems': None, 'commentTextItems': [{'type': 'HTML', 'html': 'slower ball, 128ks, Rana beaten as he moves around to manufacture a shot'}], 'commentPostTextItems': None, 'commentVideos': [], 'commentImages': [], 'events': [], 'over': None, 'batsmanStatText': None, 'bowlerStatText': None}, {'_uid': 42734630, 'id': 42734630, 'inningNumber': 2, 'ballsActual': None, 'ballsUnique': None, 'oversUnique': 18.01, 'oversActual': 18.1, 'overNumber': 19, 'ballNumber': 1, 'totalRuns': 1, 'batsmanRuns': 1, 'isFour': False, 'isSix': False, 'isWicket': False, 'dismissalType': None, 'byes': 0, 'legbyes': 0, 'wides': 0, 'noballs': 0, 'penalties': 0, 'wagonZone': 4, 'timestamp': '2023-05-14T17:35:54.000Z', 'modified': '2023-05-14T17:35:58.000Z', 'batsmanPlayerId': 51012, 'bowlerPlayerId': 80607, 'outPlayerId': None, 'totalInningRuns': 142, 'totalInningWickets': 4, 'predictions': {'score': 162, 'winProbability': 99.71}, 'title': 'Deshpande to Russell', 'dismissalText': None, 'commentPreTextItems': [{'type': 'HTML', 'html': 'Just four needed in the last two. Deshpande to bowl'}], 'commentTextItems': [{'type': 'HTML', 'html': 'low full toss as he tries a yorker. Driven to long-on for one'}], 'commentPostTextItems': None, 'commentVideos': [], 'commentImages': [], 'events': [], 'over': None, 'batsmanStatText': None, 'bowlerStatText': None}]

In [148]:


for end_over in np.arange(2,22,2):
    print(end_over)

for inning_num in np.arange(1,3):
    print(inning_num)

2
4
6
8
10
12
14
16
18
20
1
2

In [154]:

#bbb_colname = ['inn','onum','bnum','tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt', 'tm.bat']
bbb_colname = ['inn','onum','bnum','tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt']

bbb_master_df = pd.DataFrame(columns = bbb_colname)


for inning_num in np.arange(1,3):
    for end_over in np.arange(2,22,2):    
        print(f'Getting data for inning_num : {inning_num}, end_over : {end_over}')

        two_overs = scrape_chunk(series_id, match_id, end_over, inning_num)


        for ball_index in np.arange(len(two_overs)):

            #print(two_overs[ball_index]['inningNumber'])
            inn = two_overs[ball_index]['inningNumber']

            #print(two_overs[ball_index]['overNumber'])
            onum = two_overs[ball_index]['overNumber']

            #print(two_overs[ball_index]['ballNumber'])
            bnum = two_overs[ball_index]['ballNumber']

            #print(two_overs[ball_index]['totalRuns'])
            tr = two_overs[ball_index]['totalRuns']
            trb = two_overs[ball_index]['batsmanRuns']
            #print(two_overs[ball_index]['id'])

            ffour = two_overs[ball_index]['isFour']
            fsix = two_overs[ball_index]['isSix']
            fwkt = two_overs[ball_index]['isWicket']
            out_type = two_overs[ball_index]['dismissalType']

            pid_bat = two_overs[ball_index]['batsmanPlayerId']
            pid_bow = two_overs[ball_index]['bowlerPlayerId']

            inn_tr = two_overs[ball_index]['totalInningRuns']
            inn_wkt = two_overs[ball_index]['totalInningWickets']

            #tm_bat = two_overs[ball_index]['over']['team']['abbreviation']

            bbb_rowlist = [inn, onum, bnum, tr, trb, ffour, fsix, fwkt, out_type, pid_bat, pid_bow, inn_tr, inn_wkt]
            bbb_master_df.loc[len(bbb_master_df)] = bbb_rowlist
            
print(bbb_master_df.shape)

Getting data for inning_num : 1, end_over : 2
Getting data for inning_num : 1, end_over : 4
Getting data for inning_num : 1, end_over : 6
Getting data for inning_num : 1, end_over : 8
Getting data for inning_num : 1, end_over : 10
Getting data for inning_num : 1, end_over : 12
Getting data for inning_num : 1, end_over : 14
Getting data for inning_num : 1, end_over : 16
Getting data for inning_num : 1, end_over : 18
Getting data for inning_num : 1, end_over : 20
Getting data for inning_num : 2, end_over : 2
Getting data for inning_num : 2, end_over : 4
Getting data for inning_num : 2, end_over : 6
Getting data for inning_num : 2, end_over : 8
Getting data for inning_num : 2, end_over : 10
Getting data for inning_num : 2, end_over : 12
Getting data for inning_num : 2, end_over : 14
Getting data for inning_num : 2, end_over : 16
Getting data for inning_num : 2, end_over : 18
Getting data for inning_num : 2, end_over : 20
(243, 13)

In [157]:

print(bbb_master_df.shape)
print()
print(bbb_master_df.columns.values.tolist())

(243, 13)

['inn', 'onum', 'bnum', 'tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt']

In [155]:
display(bbb_master_df)

,inn,onum,bnum,tr,trb,ffour,fsix,fwkt,out.type,pid.bat,pid.bow,inn.tr,inn.wkt
0,1,2,6,2,2,False,False,False,None,95094,111976,17,0
1,1,2,5,1,1,False,False,False,None,58403,111976,15,0
2,1,2,4,4,4,True,False,False,None,58403,111976,14,0
3,1,2,3,1,1,False,False,False,None,95094,111976,10,0
4,1,2,2,0,0,False,False,False,None,95094,111976,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,2,17,1,1,1,False,False,False,None,70411,101991,127,3
239,2,19,4,4,4,True,False,False,None,70411,80607,147,4
240,2,19,3,1,0,False,False,False,None,70411,80607,143,4
241,2,19,2,0,0,False,False,False,None,70411,80607,142,4
242,2,19,1,1,1,False,False,False,None,51012,80607,142,4

In [171]:

#print(two_overs[0]['oversActual'])

overs_actual_list = ['19.6','18.6','17.6','16.6','15.6','14.6','13.6','12.6','11.6','10.6','9.6','8.6','7.6','6.6','5.6','4.6','3.6','2.6','1.6','0.6']

#if '19.6' in overs_actual_list:
#    print('19.6')

col_bat_master = ['p.nm', 'bat.style', 'bow.style', 'c.id', 'p.id']

pmaster_df = pd.DataFrame(columns=col_bat_master)
display(pmaster_df)


for inning_num in np.arange(1,3):
    for end_over in np.arange(2,22,2):
        print(f'Getting data for inning_num : {inning_num}, end_over : {end_over}')
        two_overs = scrape_chunk(series_id, match_id, end_over, inning_num)

        print('Batsmen this over')
        if str(two_overs[0]['oversActual']) in overs_actual_list:
            #print(two_overs[0]['oversActual'])

            obats = len(two_overs[0]['over']['overEndBatsmen'])
            #print(obats)
            #print()

            for obat_ind in np.arange(obats):
                #pprint(two_overs[0]['over']['overEndBatsmen'][obat_ind])
                cbat = two_overs[0]['over']['overEndBatsmen'][obat_ind]['player']

                print(cbat['battingName'])
                bat_nm = cbat['battingName']

                print(cbat['battingStyles'])
                bat_style= cbat['battingStyles'][0]

                if len(cbat['bowlingStyles']) > 0:
                    print(cbat['bowlingStyles'])
                    bow_style= cbat['bowlingStyles'][0]
                else:
                    bow_style = None

                print(cbat['countryTeamId'])
                c_id = cbat['countryTeamId']

                print(cbat['id'])
                bat_id = cbat['id']

                bat_row = [ bat_nm ,bat_style , bow_style, c_id, bat_id ]
                print(bat_row)

                print()
                print()
                
                pmaster_df.loc[len(pmaster_df)] = bat_row

        print()
        print()
        print('Bowler this over')
        print()

        if str(two_overs[0]['oversActual']) in overs_actual_list:
            for obow in two_overs[0]['over']['overEndBowlers']:
                #pprint(obows)
                #pprint(two_overs[0]['over']['overEndBowlers'][obat_ind])
                cbow = obow['player']

                print(cbow['battingName'])
                bow_nm = cbow['battingName']

                print(cbow['battingStyles'])
                bat_style= cbow['battingStyles'][0]

                if len(cbow['bowlingStyles']) > 0:
                    print(cbow['bowlingStyles'])
                    bow_style= cbow['bowlingStyles'][0]
                else:
                    bow_style = None

                print(cbow['countryTeamId'])
                c_id = cbow['countryTeamId']

                print(cbow['id'])
                bow_id = cbow['id']

                bow_row = [ bow_nm , bat_style, bow_style , c_id, bow_id ]
                print(bow_row)
                
                print()
                print()

                pmaster_df.loc[len(pmaster_df)] = bow_row

        #obo_colname = ['inn','onum', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt', 'tm.bat']
        #bbb_rowlist = [inn, onum, bnum, tr, trb, ffour, fsix, fwkt, out_type, pid_bat, pid_bow, inn_tr, inn_wkt, tm_bat]

        
print(pmaster_df.shape)
pmaster = pmaster_df.sort_values(by = 'p.nm').drop_duplicates(inplace = False)
print(pmaster.shape)

Empty DataFrame
Columns: [p.nm, bat.style, bow.style, c.id, p.id]
Index: []

Getting data for inning_num : 1, end_over : 2
Batsmen this over
RD Gaikwad
['rhb']
['ob']
6
95094
['RD Gaikwad', 'rhb', 'ob', 6, 95094]


DP Conway
['lhb']
['rm']
5
58403
['DP Conway', 'lhb', 'rm', 5, 58403]




Bowler this over

Harshit Rana
['rhb']
['rmf']
6
111976
['Harshit Rana', 'rhb', 'rmf', 6, 111976]


VG Arora
['rhb']
['rfm']
6
107007
['VG Arora', 'rhb', 'rfm', 6, 107007]


Getting data for inning_num : 1, end_over : 4
Batsmen this over
DP Conway
['lhb']
['rm']
5
58403
['DP Conway', 'lhb', 'rm', 5, 58403]


AM Rahane
['rhb']
['rm']
6
51096
['AM Rahane', 'rhb', 'rm', 6, 51096]




Bowler this over

CV Varun
['rhb']
['lbg']
6
98673
['CV Varun', 'rhb', 'lbg', 6, 98673]


VG Arora
['rhb']
['rfm']
6
107007
['VG Arora', 'rhb', 'rfm', 6, 107007]


Getting data for inning_num : 1, end_over : 6
Batsmen this over
DP Conway
['lhb']
['rm']
5
58403
['DP Conway', 'lhb', 'rm', 5, 58403]


AM Rahane
['rhb']
['rm']
6
51096
['AM Rahane', 'rhb', 'rm', 6, 51096]




Bowler this over

VG Arora
['rhb']
['rfm']
6
107007
['VG Arora', 'rhb', 'rfm', 6, 107007]


Harshit Rana
['rhb']
['rmf']
6
111976
['Harshit Rana', 'rhb', 'rmf', 6, 111976]


Getting data for inning_num : 1, end_over : 8
Batsmen this over
DP Conway
['lhb']
['rm']
5
58403
['DP Conway', 'lhb', 'rm', 5, 58403]




Bowler this over

CV Varun
['rhb']
['lbg']
6
98673
['CV Varun', 'rhb', 'lbg', 6, 98673]


SP Narine
['lhb']
['ob']
4
49039
['SP Narine', 'lhb', 'ob', 4, 49039]


Getting data for inning_num : 1, end_over : 10
Batsmen this over
S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]


AT Rayudu
['rhb']
['ob']
6
8999
['AT Rayudu', 'rhb', 'ob', 6, 8999]




Bowler this over

SN Thakur
['rhb']
['rm']
6
63477
['SN Thakur', 'rhb', 'rm', 6, 63477]


SP Narine
['lhb']
['ob']
4
49039
['SP Narine', 'lhb', 'ob', 4, 49039]


Getting data for inning_num : 1, end_over : 12
Batsmen this over
S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]


RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]




Bowler this over

Suyash Sharma
['rhb']
['lbg']
6
114312
['Suyash Sharma', 'rhb', 'lbg', 6, 114312]


SP Narine
['lhb']
['ob']
4
49039
['SP Narine', 'lhb', 'ob', 4, 49039]


Getting data for inning_num : 1, end_over : 14
Batsmen this over
RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]


S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]




Bowler this over

Suyash Sharma
['rhb']
['lbg']
6
114312
['Suyash Sharma', 'rhb', 'lbg', 6, 114312]


SP Narine
['lhb']
['ob']
4
49039
['SP Narine', 'lhb', 'ob', 4, 49039]


Getting data for inning_num : 1, end_over : 16
Batsmen this over
S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]


RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]




Bowler this over

SN Thakur
['rhb']
['rm']
6
63477
['SN Thakur', 'rhb', 'rm', 6, 63477]


CV Varun
['rhb']
['lbg']
6
98673
['CV Varun', 'rhb', 'lbg', 6, 98673]


Getting data for inning_num : 1, end_over : 18
Batsmen this over
S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]


RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]




Bowler this over

CV Varun
['rhb']
['lbg']
6
98673
['CV Varun', 'rhb', 'lbg', 6, 98673]


Suyash Sharma
['rhb']
['lbg']
6
114312
['Suyash Sharma', 'rhb', 'lbg', 6, 114312]


Getting data for inning_num : 1, end_over : 20
Batsmen this over
MS Dhoni
['rhb']
['rm']
6
7593
['MS Dhoni', 'rhb', 'rm', 6, 7593]


S Dube
['lhb']
['rm']
6
74975
['S Dube', 'lhb', 'rm', 6, 74975]




Bowler this over

VG Arora
['rhb']
['rfm']
6
107007
['VG Arora', 'rhb', 'rfm', 6, 107007]


SN Thakur
['rhb']
['rm']
6
63477
['SN Thakur', 'rhb', 'rm', 6, 63477]


Getting data for inning_num : 2, end_over : 2
Batsmen this over
JJ Roy
['rhb']
1
52290
['JJ Roy', 'rhb', None, 1, 52290]


VR Iyer
['lhb']
['rm']
6
81147
['VR Iyer', 'lhb', 'rm', 6, 81147]




Bowler this over

TU Deshpande
['lhb']
['rm']
6
80607
['TU Deshpande', 'lhb', 'rm', 6, 80607]


DL Chahar
['rhb']
['rm']
6
62022
['DL Chahar', 'rhb', 'rm', 6, 62022]


Getting data for inning_num : 2, end_over : 4
Batsmen this over
N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]


JJ Roy
['rhb']
1
52290
['JJ Roy', 'rhb', None, 1, 52290]




Bowler this over

TU Deshpande
['lhb']
['rm']
6
80607
['TU Deshpande', 'lhb', 'rm', 6, 80607]


DL Chahar
['rhb']
['rm']
6
62022
['DL Chahar', 'rhb', 'rm', 6, 62022]


Getting data for inning_num : 2, end_over : 6
Batsmen this over
RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]


N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]




Bowler this over

TU Deshpande
['lhb']
['rm']
6
80607
['TU Deshpande', 'lhb', 'rm', 6, 80607]


DL Chahar
['rhb']
['rm']
6
62022
['DL Chahar', 'rhb', 'rm', 6, 62022]


Getting data for inning_num : 2, end_over : 8
Batsmen this over
N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]


RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]




Bowler this over

M Theekshana
['rhb']
['ob']
8
101991
['M Theekshana', 'rhb', 'ob', 8, 101991]


MM Ali
['lhb']
['ob']
1
46597
['MM Ali', 'lhb', 'ob', 1, 46597]


Getting data for inning_num : 2, end_over : 10
Batsmen this over
RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]


N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]




Bowler this over

M Pathirana
['rhb']
['rf']
8
105938
['M Pathirana', 'rhb', 'rf', 8, 105938]


MM Ali
['lhb']
['ob']
1
46597
['MM Ali', 'lhb', 'ob', 1, 46597]


Getting data for inning_num : 2, end_over : 12
Batsmen this over
RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]


N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]




Bowler this over

RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]


MM Ali
['lhb']
['ob']
1
46597
['MM Ali', 'lhb', 'ob', 1, 46597]


Getting data for inning_num : 2, end_over : 14
Batsmen this over
RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]


N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]




Bowler this over

RA Jadeja
['lhb']
['sla']
6
49247
['RA Jadeja', 'lhb', 'sla', 6, 49247]


MM Ali
['lhb']
['ob']
1
46597
['MM Ali', 'lhb', 'ob', 1, 46597]


Getting data for inning_num : 2, end_over : 16
Batsmen this over
RK Singh
['lhb']
['ob']
6
75591
['RK Singh', 'lhb', 'ob', 6, 75591]


N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]




Bowler this over

M Pathirana
['rhb']
['rf']
8
105938
['M Pathirana', 'rhb', 'rf', 8, 105938]


M Theekshana
['rhb']
['ob']
8
101991
['M Theekshana', 'rhb', 'ob', 8, 101991]


Getting data for inning_num : 2, end_over : 18
Batsmen this over
N Rana
['lhb']
['rm', 'ob', 'lb']
6
70411
['N Rana', 'lhb', 'rm', 6, 70411]


AD Russell
['rhb']
['rf']
4
51012
['AD Russell', 'rhb', 'rf', 4, 51012]




Bowler this over

M Pathirana
['rhb']
['rf']
8
105938
['M Pathirana', 'rhb', 'rf', 8, 105938]


M Theekshana
['rhb']
['ob']
8
101991
['M Theekshana', 'rhb', 'ob', 8, 101991]


Getting data for inning_num : 2, end_over : 20
Batsmen this over


Bowler this over

(75, 5)
(23, 5)

In [172]:

print(pmaster.shape)
print(pmaster.columns.values.tolist())

(23, 5)
['p.nm', 'bat.style', 'bow.style', 'c.id', 'p.id']

In [174]:

display(pmaster)

             p.nm bat.style bow.style c.id    p.id
72     AD Russell       rhb        rf    4   51012
9       AM Rahane       rhb        rm    6   51096
16      AT Rayudu       rhb        ob    6    8999
33       CV Varun       rhb       lbg    6   98673
46      DL Chahar       rhb        rm    6   62022
8       DP Conway       lhb        rm    5   58403
11   Harshit Rana       rhb       rmf    6  111976
44         JJ Roy       rhb      None    1   52290
57    M Pathirana       rhb        rf    8  105938
53   M Theekshana       rhb        ob    8  101991
54         MM Ali       lhb        ob    1   46597
35       MS Dhoni       rhb        rm    6    7593
71         N Rana       lhb        rm    6   70411
20      RA Jadeja       lhb       sla    6   49247
0      RD Gaikwad       rhb        ob    6   95094
59       RK Singh       lhb        ob    6   75591
36         S Dube       lhb        rm    6   74975
17      SN Thakur       rhb        rm    6   63477
18      SP Narine       lhb        ob    4   49039
21  Suyash Sharma       rhb       lbg    6  114312
45   TU Deshpande       lhb        rm    6   80607
10       VG Arora       rhb       rfm    6  107007
40        VR Iyer       lhb        rm    6   81147

In [175]:

print(bbb_master_df.columns.values.tolist())
print(pmaster.columns.values.tolist())

bat_cols = ['p.nm','bat.style','p.id']
bow_cols = ['p.nm','bow.style','p.id']

master_interim = pd.merge( bbb_master_df, pmaster[bat_cols], left_on = ['pid.bat'], right_on = ['p.id'], how = 'left' )\
            .rename(columns = {'p.nm':'bat_nm'}).drop(columns = ['p.id'])

print()
print(master_interim.columns.values.tolist())

master_df = pd.merge( master_interim, pmaster[bow_cols], left_on = ['pid.bow'], right_on = ['p.id'], how = 'left' )\
            .rename(columns = {'p.nm':'bow_nm'}).drop(columns = ['p.id'])
print()
print(master_df.columns.values.tolist())

#bbb_master_interim = pd.merge( bbb_master_interim, pmaster_df, left_on = ['pid.bat'], right_on = ['p.id'], how = 'left' )

['inn', 'onum', 'bnum', 'tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt']
['p.nm', 'bat.style', 'bow.style', 'c.id', 'p.id']

['inn', 'onum', 'bnum', 'tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt', 'bat_nm', 'bat.style']

['inn', 'onum', 'bnum', 'tr', 'trb', 'ffour', 'fsix', 'fwkt', 'out.type', 'pid.bat', 'pid.bow', 'inn.tr', 'inn.wkt', 'bat_nm', 'bat.style', 'bow_nm', 'bow.style']

In [176]:

display(master_df.head(3))

,inn,onum,bnum,tr,trb,ffour,fsix,fwkt,out.type,pid.bat,pid.bow,inn.tr,inn.wkt,bat_nm,bat.style,bow_nm,bow.style
0,1,2,6,2,2,False,False,False,None,95094,111976,17,0,RD Gaikwad,rhb,Harshit Rana,rmf
1,1,2,5,1,1,False,False,False,None,58403,111976,15,0,DP Conway,lhb,Harshit Rana,rmf
2,1,2,4,4,4,True,False,False,None,58403,111976,14,0,DP Conway,lhb,Harshit Rana,rmf

In [178]:

exp_location = "C:\\Users\\karan\\Documents\\Cricket-Analytics\\IPL\\Data\\bbb_ecric\\"
exp_mname = "G61_KKR v CSK"
exp_ext = ".xlsx"

master_df.to_excel(exp_location + exp_mname + exp_ext, index = False)